-- The three tables production made by hand before the migration files
-- existed: the old nav/footer link list, the site scripts, and the video
-- list from before the catalog. The app reads none of them any more, but
-- production still has them, and a database rebuilt from these files
-- (staging, 12 September 2026) did not, so 0005's policies fell over and the
-- migrations were not the complete history they claimed to be. They are.
--
-- Shapes copied from production. No rebuild triggers: those called a deploy
-- hook, and a staging database must never deploy anything.

create table if not exists public.site_links (
  id        bigint generated by default as identity primary key,
  area      text not null check (area in ('header','services','footer_company','footer_brands','legal','social')),
  label     text not null,
  href      text not null,
  sort      integer not null default 0,
  enabled   boolean not null default true,
  external  boolean not null default false
);
alter table public.site_links enable row level security;
drop policy if exists "anon read links" on public.site_links;
create policy "anon read links" on public.site_links for select to anon using (true);
drop policy if exists site_links_admin_read on public.site_links;
create policy site_links_admin_read on public.site_links
  for select to authenticated using (public.is_admin());
drop policy if exists site_links_admin_write on public.site_links;
create policy site_links_admin_write on public.site_links
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.site_settings (
  id               integer primary key default 1 check (id = 1),
  head_scripts     text not null default '',
  body_end_scripts text not null default '',
  updated_at       timestamptz not null default now()
);
alter table public.site_settings enable row level security;
drop policy if exists "anon read settings" on public.site_settings;
create policy "anon read settings" on public.site_settings for select to anon using (true);
drop policy if exists site_settings_admin_read on public.site_settings;
create policy site_settings_admin_read on public.site_settings
  for select to authenticated using (public.is_admin());
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_admin_write on public.site_settings
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.videos (
  id            bigint generated by default as identity primary key,
  title         text not null,
  library       text not null default 'new' check (library in ('new','classic')),
  video_type    text not null default '',
  category      text not null default '',
  video_url     text not null default '',
  checkout_url  text not null default '',
  price         numeric,
  on_site       boolean not null default false,
  notes         text not null default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
alter table public.videos enable row level security;
drop policy if exists videos_admin_all on public.videos;
create policy videos_admin_all on public.videos
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
